alias ap="ansible-playbook"
alias be="bundle exec"
alias bi="bundler install"
alias c="cucumber"
alias com="git commit"
alias cs="cd ~/src"
alias ga="git add"
alias gb="git branch"
alias gcl="git clone"
alias gco="git checkout"
alias gdc="git diff --cached"
alias gfa="git fetch --all"
alias gl="git log"
alias gplr="git pull --rebase"
alias gs="git status"
alias i=irb
alias p=python
alias ru=ruby
alias r=rails
alias t="rake test"
alias sb="source ~/.bashrc"
